# Generated by Django 3.1.7 on 2021-06-15 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensageiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariocadastrado',
            name='fromId',
            field=models.BigIntegerField(unique=True),
        ),
    ]
